---
title: "p8105_hw2_sc5078"
author: "Yvonne Chen"
date: "2023-10-03"
output: github_document
---

# Problem 1
Load the tidyverse library
```{r setup, include = FALSE}
library(tidyverse)
```

Import three datasets
```{r clean pols_month}
## finds my current working directory
getwd()

## Import and clean pols_month.cvs datasets
pols_month = read.csv("./fivethirtyeight_datasets/pols-month.csv") |>
  janitor::clean_names()|>
  separate(mon, into=c("year", "month", "day"), convert = TRUE) |>
  mutate(
    month = month.name[month],
    president = 
      case_match(
        prez_gop, 
        0 ~ "democratic",
        1 ~ "republican", 
        2 ~ "republican"),
    president = as.factor(president)) |>
  select(-day, -prez_dem,-prez_gop)
```

```{r clean snp}
## Import and clean snp.csv datasets
snp = read.csv("./fivethirtyeight_datasets/snp.csv") |>
  janitor::clean_names()|>
  separate(date, into=c("month", "day", "year"), convert = TRUE) |>
  arrange(year, month) |>
  mutate(
    year = year + 2000,
    month = month.name[month]) |>
  select(year, month, close)

```





